stages:
  - build:rpm
  - publish_rpm

before_script:
  - export RICHACL_BUILD_ID=${CI_PIPELINE_ID}git${CI_COMMIT_SHA:0:8}
  - echo "Exporting RICHACL_BUILD_ID=${RICHACL_BUILD_ID}"
  - test -n "${CI_COMMIT_TAG}" && export TAG_MAJOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_.*/\1.\2/')
  - test -n "${CI_COMMIT_TAG}" && export TAG_MINOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_//;s/_/./')

variables:
  SAMBAVERSION: "4.13.3"    # also supported "4.11" and "4.12"


## Builds ##

# SRPM and RPM, non-tagged builds
sambarichacl_rpm:
  except:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  script:
    - cp *8.repo /etc/yum.repos.d
    - dnf install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel perl-interpreter wget
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS
    - bash -x ./samba_richacl_build.sh samba-$SAMBAVERSION tgz
    - rpmbuild -bb ~/rpmbuild/SPECS/samba.spec
    - cp ~/rpmbuild/SRPMS/*.src.rpm ~/rpmbuild/RPMS/x86_64/*rpm RPMS
  artifacts:
    expire_in: 7 days
    paths:
      - RPMS
  tags:
    - docker_node


# SRPM and RPM, tagged builds
sambarichacl_tagged_rpm_cc7:
  only:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - echo "Building package for tag ${CI_COMMIT_TAG}"
    - cp *7.repo /etc/yum.repos.d
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel perl-interpreter wget
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS_cc7
    - bash -x ./samba_richacl_build.sh samba-${CI_COMMIT_TAG} srpm
    - rpm -i ~/rpmbuild/SRPMS/samba_richacl*.src.rpm
    - sh ~/rpmbuild/SOURCES/samba_richacl_build.sh samba-${CI_COMMIT_TAG}
    - cp ~/rpmbuild/SRPMS/samba_richacl*.src.rpm ~/rpmbuild/RPMS/x86_64/samba_richacl*rpm RPMS_cc7
  artifacts:
    expire_in: 30 days
    paths:
      - RPMS_cc7
  tags:
    - docker_node


sambarichacl_tagged_rpm_c8:
  only:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - echo "Building package for tag ${CI_COMMIT_TAG}"
    - cp *8.repo /etc/yum.repos.d
    - dnf install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel perl-interpreter wget
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS_c8
    - bash -x ./samba_richacl_build.sh samba-${CI_COMMIT_TAG} srpm
    - rpm -i ~/rpmbuild/SRPMS/samba_richacl*.src.rpm
    - sh ~/rpmbuild/SOURCES/samba_richacl_build.sh samba-${CI_COMMIT_TAG}
    - cp ~/rpmbuild/SRPMS/samba_richacl*.src.rpm ~/rpmbuild/RPMS/x86_64/samba_richacl*rpm RPMS_c8
  artifacts:
    expire_in: 30 days
    paths:
      - RPMS_c8
  tags:
    - docker_node


## Publishing ##

publish_tagged_rpm:
  stage: publish_rpm
  only:
    - tags
  except:
    - schedules
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - yum install -y sudo sssd-client createrepo
    - sudo -u stci -H ./gitlab-ci/publish_rpms.sh
  tags:
    - docker_node
  dependencies:
    - sambarichacl_tagged_rpm_cc7
    - sambarichacl_tagged_rpm_c8
