stages:
  - build:rpm
  - publish_rpm

before_script:
  - export RICHACL_BUILD_ID=${CI_PIPELINE_ID}git${CI_COMMIT_SHA:0:8}
  - echo "Exporting RICHACL_BUILD_ID=${RICHACL_BUILD_ID}"
  - test -n "${CI_COMMIT_TAG}" && export TAG_MAJOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_.*/\1.\2/')
  - test -n "${CI_COMMIT_TAG}" && export TAG_MINOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_//;s/_/./')


variables:
    SAMBAVERSION: "4.10.4"    # also supported "4.9.1" and "4.8.3"


## Builds ##

# SRPM and RPM, non-tagged builds
sambarichacl_rpm:
  except:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - cp *.repo /etc/yum.repos.d
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS
    - bash -x ./samba_richacl_build.sh samba-$SAMBAVERSION srpm
    - rpm -i ~/rpmbuild/SRPMS/samba_richacl*.src.rpm
    - sh -x ~/rpmbuild/SOURCES/samba_richacl_build.sh samba-$SAMBAVERSION
    - cp ~/rpmbuild/SRPMS/samba_richacl*.src.rpm ~/rpmbuild/RPMS/x86_64/samba_richacl*rpm RPMS

  artifacts:
    expire_in: 15 days
    paths:
      - RPMS

  tags:
    - docker_node


# SRPM and RPM, tagged builds
sambarichacl_tagged_rpm:
  only:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - echo "Building package for tag ${CI_COMMIT_TAG}"
    - cp *.repo /etc/yum.repos.d
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS
    - bash -x ./samba_richacl_build.sh samba-${CI_COMMIT_TAG} srpm
    - rpm -i ~/rpmbuild/SRPMS/samba_richacl*.src.rpm
    - sh ~/rpmbuild/SOURCES/samba_richacl_build.sh samba-${CI_COMMIT_TAG}
    - cp ~/rpmbuild/SRPMS/samba_richacl*.src.rpm ~/rpmbuild/RPMS/x86_64/samba_richacl*rpm RPMS

  artifacts:
    expire_in: 180 days
    paths:
      - RPMS

  tags:
    - docker_node


## Publishing ##

publish_tagged_rpm:
  stage: publish_rpm
  only:
    - tags
  except:
    - schedules
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - yum install -y sudo sssd-client createrepo
    - sudo -u stci -H cp RPMS/*src.rpm /eos/project/s/storage-ci/www/cernbox/tag/el-7/SRPMS/
    - sudo -u stci -H cp RPMS/*x86_64.rpm /eos/project/s/storage-ci/www/cernbox/tag/el-7/x86_64/
  tags:
    - docker_node
