stages:
  - build:srpm
  - build:rpm
  - publish_rpm

before_script:
  - export RICHACL_BUILD_ID=${CI_PIPELINE_ID}git${CI_COMMIT_SHA:0:8}
  - echo "Exporting RICHACL_BUILD_ID=${RICHACL_BUILD_ID}"
  - test -n "${CI_COMMIT_TAG}" && export TAG_MAJOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_.*/\1.\2/')
  - test -n "${CI_COMMIT_TAG}" && export TAG_MINOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_//;s/_/./')


## Builds ##

# SRPM for all builds
sambarichacl_srpm:
  stage: build:srpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install -y rpm-build yum-utils
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS}
    - cp *c *sh ~/rpmbuild/SOURCES/
    - cp *spec ~/rpmbuild/SPECS/
    - rpmbuild -bs ~/rpmbuild/SPECS/samba_richacl.spec

  artifacts:
    expire_in: 15 days
    paths:
    - /root/rpmbuild/SRPMS/samba_richacl*.src.rpm

  tags:
    - docker

# All RPMs, non-tagged builds
sambarichacl_rpm:
  except:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS}
    - cp *c *sh ~/rpmbuild/SOURCES/
    - cp *spec ~/rpmbuild/SPECS/
#    - yum-config-manager --enable cernonly
#    - yum-builddep --nogpgcheck -y rpmbuild/SRPMS/*
    - sh ~/rpmbuild/SOURCES/samba_richacl_build.sh

  artifacts:
    expire_in: 15 days
    paths:
    - /root/rpmbuild/RPMS/x86_64/samba_richacl*rpm

  tags:
    - docker

# All RPMs, tagged builds
sambarichacl_tagged_rpm:
  only:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - echo "Building package for tag ${CI_COMMIT_TAG}"
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel
#    - yum-config-manager --enable cernonly
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS}
    - cp *c *sh ~/rpmbuild/SOURCES/
    - cp *spec ~/rpmbuild/SPECS/
    - sh ~/rpmbuild/SOURCES/samba_richacl_build.sh

  artifacts:
    expire_in: 180 days
    paths:
    - /root/rpmbuild/RPMS/x86_64/samba_richacl*rpm

  tags:
    - docker


## Publishing ##

# Tagged builds
publish_tagged_rpm:
  stage: publish_rpm
  only:
    - tags
  except:
    - schedules
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - cp ~/rpmbuild/SRPMS/*src.rpm ~/rpmbuild/RPMS/
    - EOS_ACCOUNT_USERNAME=${LOGIN_USERNAME} EOS_ACCOUNT_PASSWORD=${LOGIN_PASSWORD} CI_OUTPUT_DIR=~/rpmbuild/RPMS EOS_PATH=/eos/project/s/storage-ci/www/cernbox/tag ci/deploy-eos.sh
  tags:
    - docker

# Nightly builds disabled
#publish_nightly_rpm:
#  stage: publish_rpm
#  only:
#    - schedules
#  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
#  script:
#    - cp build_srpm/RPM/SRPMS/*src.rpm build_rpm/RPM/RPMS
#    - EOS_ACCOUNT_USERNAME=${LOGIN_USERNAME} EOS_ACCOUNT_PASSWORD=${LOGIN_PASSWORD} CI_OUTPUT_DIR=~/rpmbuild/RPMS EOS_PATH=/eos/project/s/storage-ci/www/cernbox/tag ci/deploy-eos.sh
#  tags:
#    - docker
