stages:
  - prebuild
  - build:rpm
  - build:richaclrpm
  - publish_rpm

before_script:
  - export RICHACL_BUILD_ID=${CI_PIPELINE_ID}git${CI_COMMIT_SHA:0:8}
  - echo "Exporting RICHACL_BUILD_ID=${RICHACL_BUILD_ID}"
  - test -n "${CI_COMMIT_TAG}" && export TAG_MAJOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_.*/\1.\2/')
  - test -n "${CI_COMMIT_TAG}" && export TAG_MINOR=$(echo ${CI_COMMIT_TAG} | sed -e 's/^v//;s/\([^_]\+\)_\([^_]\+\)_//;s/_/./')

variables:
  SAMBAVERSION: "4.13.4"    # also supported "4.11" and "4.12"


## Pre-builds ##


# Use the docker image coming out from this stage as an input base image for the build stages
.prebuid-template: &prebuild-template_definition
  stage: prebuild
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export DESTINATION="gitlab-registry.cern.ch/dss/samba-richacl/prebuild-${PREBUILD_NAME}"
    - export DOCKERFILE="$CI_PROJECT_DIR/gitlab-ci/prebuild-${PREBUILD_NAME}.Dockerfile"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache="false" --destination $DESTINATION --dockerfile $DOCKERFILE --context $CI_PROJECT_DIR
  only:
    variables:
      - $PREBUILD_TRIGGER


prebuild-c8:
  <<: *prebuild-template_definition
  variables:
    PREBUILD_NAME: c8


## Builds ##


# SRPM and RPM, non-tagged builds
samba_rpm_w_ccache:
  except:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/dss/samba-richacl/prebuild-c8
  script:
    - if [[ -n "$CI_COMMIT_TAG" ]]; then export CCACHE_DISABLE=1; else source gitlab-ci/setup_ccache.sh; fi
    - cp *8.repo /etc/yum.repos.d
    - dnf install -y $(cat ./dnf-install-list)
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS}
    - date
    - bash -x ./samba_richacl_build.sh samba-$SAMBAVERSION tgz | ts
    - date
    - rpmbuild -bb ~/rpmbuild/SPECS/samba.spec | ts
    - ccache -s
    - date
    - mkdir ${CI_JOB_NAME}_artifacts;
    - cp -R ~/rpmbuild/SRPMS/*.src.rpm ~/rpmbuild/RPMS/x86_64/*rpm ~/rpmbuild/RPMS/noarch/*rpm ${CI_JOB_NAME}_artifacts
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - ccache/
  artifacts:
    expire_in: 7 days
    paths:
      - "${CI_JOB_NAME}_artifacts"
  tags:
    - docker_node


samba_rpm:
  except:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/dss/samba-richacl/prebuild-c8
  script:
    - if [[ -n "$CI_COMMIT_TAG" ]]; then export CCACHE_DISABLE=1; else source gitlab-ci/setup_ccache.sh; fi
    - if [ -d cache/BUILD ]; then echo "Found cache, skipping build"; exit 0; fi
    - cp *8.repo /etc/yum.repos.d
    - dnf install -y $(cat ./dnf-install-list)
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS
    - bash -x ./samba_richacl_build.sh samba-$SAMBAVERSION tgz
    - rpmbuild -bb ~/rpmbuild/SPECS/samba.spec
    - cp ~/rpmbuild/SRPMS/*.src.rpm ~/rpmbuild/RPMS/x86_64/*rpm ~/rpmbuild/RPMS/noarch/*rpm RPMS
    - cp -r ~/rpmbuild/BUILD cache/
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - cache/
  artifacts:
    expire_in: 7 days
    paths:
      - RPMS
  tags:
    - docker_node

richacl_rpm:
  except:
    - tags
  stage: build:richaclrpm
  image: gitlab-registry.cern.ch/dss/samba-richacl/prebuild-c8
  script:
    - cp *8.repo /etc/yum.repos.d
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel perl-interpreter wget
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS}
    - cp -r cache/BUILD ~/rpmbuild/
    - bash -x ./samba_richacl_build.sh samba-$SAMBAVERSION srpm
    - cp ~/rpmbuild/SRPMS/samba_richacl*.src.rpm ~/rpmbuild/RPMS/x86_64/samba_richacl*rpm RPMS
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - cache/
  artifacts:
    expire_in: 7 days
    paths:
      - RPMS
  tags:
    - docker_node
  dependencies:
    - samba_rpm


# SRPM and RPM, tagged builds
samba_tagged_rpm_cc7:
  only:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - echo "Building package for tag ${CI_COMMIT_TAG}"
    - cp *7.repo /etc/yum.repos.d
    - yum install -y gcc-c++ cmake make rpm-build yum-utils librichacl librichacl-devel perl-interpreter wget
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS_cc7
  artifacts:
    expire_in: 30 days
    paths:
      - RPMS_cc7
  tags:
    - docker_node


samba_tagged_rpm_c8:
  only:
    - tags
  stage: build:rpm
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - echo "Building packages for tag ${CI_COMMIT_TAG}"
    - cp *8.repo /etc/yum.repos.d
    - dnf install -y $(cat ./dnf-install-list)
    - mkdir -p ~/rpmbuild/{SOURCES,SPECS} RPMS_c8
    - bash -x ./samba_richacl_build.sh samba-${CI_COMMIT_TAG} tgz
    - rpmbuild -bb ~/rpmbuild/SPECS/samba.spec
    - cp ~/rpmbuild/SRPMS/*.src.rpm ~/rpmbuild/RPMS/x86_64/*rpm ~/rpmbuild/RPMS/noarch/*rpm RPMS_c8
  artifacts:
    expire_in: 30 days
    paths:
      - RPMS_c8
  tags:
    - docker_node


## Publishing ##

publish_tagged_rpm:
  stage: publish_rpm
  only:
    - tags
  except:
    - schedules
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - if [ -z "${CI_COMMIT_TAG}" ]; then echo "This is not a tagged commit, exiting"; exit 0; fi
    - yum install -y sudo sssd-client createrepo
    - sudo -u stci -H ./gitlab-ci/publish_rpms.sh
  tags:
    - docker_node
  dependencies:
#   - samba_tagged_rpm_cc7
    - samba_tagged_rpm_c8
